resolver: lts-19.8 # ghc-9.0.2
extra-deps:
- ghc-lib-parser-0.20220501
ghc-options:
    "$locals": -ddump-to-file -ddump-hi -Wall -Wno-name-shadowing -Wunused-imports
flags:
  ghc-lib-parser-ex:
    auto: false
    no-ghc-lib: false
  mintty:
    Win32-2-13-1: false

# Packages MUST go at the end, since we append to it during execution
# of CI.hs.
packages:
- .
