name: hlint-check
on:
  push:
  pull_request:
jobs:
  hlint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [GHC_8_8, GHC_8_10, GHC_9_0, GHC_9_2, GHC_9_4, GHC_9_6, GHC_9_8, GHC_9_10, GHC_9_12, GHC_9_14]
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/hlint-setup@v2
      with:
        version: '3.8'
    - name: 'ghc-lib-parser-ex'
      uses: haskell-actions/hlint-run@v2
      with:
        hlint-bin: hlint --cpp-include cbits --cpp-define ${{matrix.version}}
        path: '["src"]'
        fail-on: warning
