name: ormolu-check
on:
  push:
  pull_request:
jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/run-ormolu@v16
        with:
          pattern: |
            src/**/*.hs
          mode: check
